#!/usr/bin/env python3
"""Generate the nominal Summer24 muon-correction lookup tables.

The input is the public Muon POG correctionlib JSON used by ZbAnalysis.  The
analysis intentionally embeds only its nominal numeric tables, avoiding a
runtime correctionlib dependency on bare ROOT/HTCondor workers.
"""

import argparse
import hashlib
import json
from pathlib import Path
from typing import Dict, List, Sequence


def nominal(category: Dict[str, object]) -> float:
    if category.get("nodetype") != "category":
        raise ValueError("expected a correctionlib category node")
    for item in category["content"]:
        if item["key"] == "nom":
            return float(item["value"])
    raise ValueError("nominal category value is missing")


def parameter_values(category: Dict[str, object], count: int) -> List[float]:
    values = [None] * count
    for item in category["content"]:
        key = int(item["key"])
        if 0 <= key < count:
            values[key] = float(item["value"])
    if any(value is None for value in values):
        raise ValueError("parameter category is incomplete")
    return values


def format_number(value: float) -> str:
    return format(value, ".17g")


def format_array(values: Sequence[float], indent: str = "  ") -> str:
    return indent + ", ".join(format_number(value) for value in values)


def matrix_rows(values: Sequence[Sequence[float]], indent: str = "  ") -> str:
    return ",\n".join(
        indent + "{" + ", ".join(format_number(value) for value in row) + "}"
        for row in values
    )


def cube_rows(values: Sequence[Sequence[Sequence[float]]]) -> str:
    blocks = []
    for block in values:
        rows = matrix_rows(block, "    ")
        blocks.append("  {\n" + rows + "\n  }")
    return ",\n".join(blocks)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    raw = args.input.read_bytes()
    payload = json.loads(raw)
    corrections = {item["name"]: item["data"]
                   for item in payload["corrections"]}
    expected = {
        "cb_params", "poly_params", "m_data", "a_data", "m_mc", "a_mc",
        "k_data", "k_mc",
    }
    if set(corrections) != expected:
        raise ValueError("unexpected Summer24 correction set")

    scale_names = ("m_data", "a_data", "m_mc", "a_mc")
    eta_edges = corrections[scale_names[0]]["edges"]
    phi_edges = corrections[scale_names[0]]["content"][0]["edges"]
    scale_tables = {}
    for name in scale_names:
        node = corrections[name]
        if node["edges"] != eta_edges:
            raise ValueError(f"inconsistent eta edges in {name}")
        rows = []
        for phi_node in node["content"]:
            if phi_node["edges"] != phi_edges:
                raise ValueError(f"inconsistent phi edges in {name}")
            rows.append([nominal(value) for value in phi_node["content"]])
        scale_tables[name] = rows

    abs_eta_edges = corrections["cb_params"]["edges"]
    layer_edges = corrections["cb_params"]["content"][0]["edges"]
    parameter_tables = {}
    for name, count in (("cb_params", 4), ("poly_params", 3)):
        node = corrections[name]
        if node["edges"] != abs_eta_edges:
            raise ValueError(f"inconsistent absolute-eta edges in {name}")
        blocks = []
        for layer_node in node["content"]:
            if layer_node["edges"] != layer_edges:
                raise ValueError(f"inconsistent tracker-layer edges in {name}")
            blocks.append([
                parameter_values(value, count)
                for value in layer_node["content"]
            ])
        parameter_tables[name] = blocks

    k_tables = {}
    for name in ("k_data", "k_mc"):
        node = corrections[name]
        if node["edges"] != abs_eta_edges:
            raise ValueError(f"inconsistent absolute-eta edges in {name}")
        k_tables[name] = [nominal(value) for value in node["content"]]

    digest = hashlib.sha256(raw).hexdigest()
    header = f"""// Generated by scripts/generate_muon_corrections.py.
// Source: {args.input.as_posix()}
// SHA256: {digest}
#ifndef ZJET_MUON_CORRECTION_DATA_H
#define ZJET_MUON_CORRECTION_DATA_H

namespace ZJetMuonCorrectionData {{

inline constexpr char sourceSha256[] = "{digest}";
inline constexpr double etaEdges[{len(eta_edges)}] = {{
{format_array(eta_edges)}
}};
inline constexpr double phiEdges[{len(phi_edges)}] = {{
{format_array(phi_edges)}
}};
inline constexpr double absoluteEtaEdges[{len(abs_eta_edges)}] = {{
{format_array(abs_eta_edges)}
}};
inline constexpr double trackerLayerEdges[{len(layer_edges)}] = {{
{format_array(layer_edges)}
}};

inline constexpr double mData[{len(eta_edges)-1}][{len(phi_edges)-1}] = {{
{matrix_rows(scale_tables['m_data'])}
}};
inline constexpr double aData[{len(eta_edges)-1}][{len(phi_edges)-1}] = {{
{matrix_rows(scale_tables['a_data'])}
}};
inline constexpr double mMc[{len(eta_edges)-1}][{len(phi_edges)-1}] = {{
{matrix_rows(scale_tables['m_mc'])}
}};
inline constexpr double aMc[{len(eta_edges)-1}][{len(phi_edges)-1}] = {{
{matrix_rows(scale_tables['a_mc'])}
}};

inline constexpr double crystalBall[{len(abs_eta_edges)-1}][{len(layer_edges)-1}][4] = {{
{cube_rows(parameter_tables['cb_params'])}
}};
inline constexpr double resolutionPolynomial[{len(abs_eta_edges)-1}][{len(layer_edges)-1}][3] = {{
{cube_rows(parameter_tables['poly_params'])}
}};
inline constexpr double kData[{len(abs_eta_edges)-1}] = {{
{format_array(k_tables['k_data'])}
}};
inline constexpr double kMc[{len(abs_eta_edges)-1}] = {{
{format_array(k_tables['k_mc'])}
}};

}} // namespace ZJetMuonCorrectionData

#endif
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="utf-8")


if __name__ == "__main__":
    main()
